<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-UtrkePasa.Server-7ee68ea1-1e2a-4c71-b445-80dd6bf8d416</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.SignalR" Version="1.2.12" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="10.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.10">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\UtrkePasa.Domain\UtrkePasa.Domain.csproj" />
    <ProjectReference Include="..\UtrkePasa.Infrastructure\UtrkePasa.Infrastructure.csproj" />
  </ItemGroup>
</Project>
