// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UtrkePasa.Domain.DataBase;

#nullable disable

namespace UtrkePasa.Domain.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260811081224_MakeDogRaceIdNullable")]
    partial class MakeDogRaceIdNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UtrkePasa.Domain.Entities.Dog", b =>
                {
                    b.Property<int>("dog_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("dog_Id"));

                    b.Property<string>("dog_Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("race_Id")
                        .HasColumnType("integer");

                    b.Property<int>("race_Odds_Id")
                        .HasColumnType("integer");

                    b.HasKey("dog_Id");

                    b.HasIndex("race_Id");

                    b.HasIndex("race_Odds_Id");

                    b.ToTable("Dog");
                });

            modelBuilder.Entity("UtrkePasa.Domain.Entities.Race", b =>
                {
                    b.Property<int>("race_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("race_Id"));

                    b.Property<DateTime>("end_Of_The_Race")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("race_Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("result_Of_Race")
                        .HasColumnType("text");

                    b.Property<DateTime>("start_Of_The_Race")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("race_Id");

                    b.ToTable("Race");
                });

            modelBuilder.Entity("UtrkePasa.Domain.Entities.RaceOdds", b =>
                {
                    b.Property<int>("race_Odds_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("race_Odds_Id"));

                    b.Property<string>("expected_Result")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("odds")
                        .HasColumnType("real");

                    b.Property<int>("race_Id")
                        .HasColumnType("integer");

                    b.Property<int?>("race_Id1")
                        .HasColumnType("integer");

                    b.HasKey("race_Odds_Id");

                    b.HasIndex("race_Id1");

                    b.ToTable("RaceOdds");
                });

            modelBuilder.Entity("UtrkePasa.Domain.Entities.Ticket", b =>
                {
                    b.Property<int>("ticket_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ticket_Id"));

                    b.Property<decimal>("paid_For_Ticket")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("placed_At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("race_Id")
                        .HasColumnType("integer");

                    b.Property<int>("race_Odds_Id")
                        .HasColumnType("integer");

                    b.Property<int>("user_Id")
                        .HasColumnType("integer");

                    b.HasKey("ticket_Id");

                    b.HasIndex("race_Id");

                    b.HasIndex("race_Odds_Id");

                    b.HasIndex("user_Id");

                    b.ToTable("Ticket");
                });

            modelBuilder.Entity("UtrkePasa.Domain.Entities.User", b =>
                {
                    b.Property<int>("user_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("user_Id"));

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("surname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("wallet_State")
                        .HasColumnType("real");

                    b.HasKey("user_Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("UtrkePasa.Domain.Entities.Dog", b =>
                {
                    b.HasOne("UtrkePasa.Domain.Entities.Race", "race")
                        .WithMany()
                        .HasForeignKey("race_Id");

                    b.HasOne("UtrkePasa.Domain.Entities.RaceOdds", "race_Odds")
                        .WithMany()
                        .HasForeignKey("race_Odds_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("race");

                    b.Navigation("race_Odds");
                });

            modelBuilder.Entity("UtrkePasa.Domain.Entities.RaceOdds", b =>
                {
                    b.HasOne("UtrkePasa.Domain.Entities.Race", "race")
                        .WithMany("odds")
                        .HasForeignKey("race_Id1");

                    b.Navigation("race");
                });

            modelBuilder.Entity("UtrkePasa.Domain.Entities.Ticket", b =>
                {
                    b.HasOne("UtrkePasa.Domain.Entities.Race", "race")
                        .WithMany("tickets")
                        .HasForeignKey("race_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UtrkePasa.Domain.Entities.RaceOdds", "race_Odds")
                        .WithMany()
                        .HasForeignKey("race_Odds_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UtrkePasa.Domain.Entities.User", "user")
                        .WithMany("tickets")
                        .HasForeignKey("user_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("race");

                    b.Navigation("race_Odds");

                    b.Navigation("user");
                });

            modelBuilder.Entity("UtrkePasa.Domain.Entities.Race", b =>
                {
                    b.Navigation("odds");

                    b.Navigation("tickets");
                });

            modelBuilder.Entity("UtrkePasa.Domain.Entities.User", b =>
                {
                    b.Navigation("tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
