// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UtrkePasa.Domain.DataBase;

#nullable disable

namespace UtrkePasa.Domain.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260821125012_AddIPAddr")]
    partial class AddIPAddr
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UtrkePasa.Domain.Entities.Dog", b =>
                {
                    b.Property<int>("DogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("dog_Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DogId"));

                    b.Property<string>("DogName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("dog_Name");

                    b.HasKey("DogId");

                    b.ToTable("Dog");
                });

            modelBuilder.Entity("UtrkePasa.Domain.Entities.Race", b =>
                {
                    b.Property<int>("RaceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("race_Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RaceId"));

                    b.PrimitiveCollection<List<string>>("DogFinalePosition")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("dog_Finale_Position");

                    b.PrimitiveCollection<List<string>>("DogStartingPosition")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("dog_Starting_Position");

                    b.Property<DateTimeOffset>("EndOfTheRace")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_Of_The_Race");

                    b.Property<string>("RaceName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("race_Name");

                    b.Property<string>("RaceStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("race_Status");

                    b.Property<string>("ResultOfRace")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("result_Of_Race");

                    b.Property<DateTimeOffset>("StartOfBetting")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_Of_Betting");

                    b.Property<DateTimeOffset>("StartOfTheRace")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_Of_The_Race");

                    b.HasKey("RaceId");

                    b.ToTable("Race");
                });

            modelBuilder.Entity("UtrkePasa.Domain.Entities.RaceOdds", b =>
                {
                    b.Property<int>("RaceOddsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("race_Odds_Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RaceOddsId"));

                    b.Property<float>("Odd")
                        .HasColumnType("real")
                        .HasColumnName("odd");

                    b.Property<int>("RaceId")
                        .HasColumnType("integer")
                        .HasColumnName("race_Id");

                    b.Property<string>("oddType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("odd_Type");

                    b.HasKey("RaceOddsId");

                    b.HasIndex("RaceId");

                    b.ToTable("RaceOdds");
                });

            modelBuilder.Entity("UtrkePasa.Domain.Entities.Register", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("appGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("app_guid");

                    b.Property<string>("appName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("app_name");

                    b.Property<string>("ipAddr")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ip_addr");

                    b.Property<DateTimeOffset?>("timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.HasKey("Id");

                    b.ToTable("Register");
                });

            modelBuilder.Entity("UtrkePasa.Domain.Entities.Ticket", b =>
                {
                    b.Property<int>("TicketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ticket_Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TicketId"));

                    b.Property<string>("ExpectedResult")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("expected_Result");

                    b.Property<bool?>("IsWinningTicket")
                        .HasColumnType("boolean")
                        .HasColumnName("is_Winning_Ticket");

                    b.Property<decimal>("PaidForTicket")
                        .HasColumnType("numeric")
                        .HasColumnName("paid_For_Ticket");

                    b.Property<DateTimeOffset>("PlacedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("placed_At");

                    b.Property<int>("RaceId")
                        .HasColumnType("integer")
                        .HasColumnName("race_Id");

                    b.Property<int>("RaceOddsId")
                        .HasColumnType("integer")
                        .HasColumnName("race_Odds_Id");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_Id");

                    b.HasKey("TicketId");

                    b.HasIndex("RaceId");

                    b.HasIndex("RaceOddsId");

                    b.HasIndex("UserId");

                    b.ToTable("Ticket");
                });

            modelBuilder.Entity("UtrkePasa.Domain.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("user_Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("surname");

                    b.Property<float>("WalletState")
                        .HasColumnType("real")
                        .HasColumnName("wallet_State");

                    b.HasKey("UserId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("UtrkePasa.Domain.Entities.RaceOdds", b =>
                {
                    b.HasOne("UtrkePasa.Domain.Entities.Race", "Race")
                        .WithMany("odds")
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Race");
                });

            modelBuilder.Entity("UtrkePasa.Domain.Entities.Ticket", b =>
                {
                    b.HasOne("UtrkePasa.Domain.Entities.Race", "Race")
                        .WithMany("tickets")
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UtrkePasa.Domain.Entities.RaceOdds", "RaceOdds")
                        .WithMany()
                        .HasForeignKey("RaceOddsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UtrkePasa.Domain.Entities.User", "User")
                        .WithMany("tickets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Race");

                    b.Navigation("RaceOdds");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UtrkePasa.Domain.Entities.Race", b =>
                {
                    b.Navigation("odds");

                    b.Navigation("tickets");
                });

            modelBuilder.Entity("UtrkePasa.Domain.Entities.User", b =>
                {
                    b.Navigation("tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
