// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UtrkePasa.Domain.DataBase;

#nullable disable

namespace UtrkePasa.Domain.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260817124926_AddProcessingTicket")]
    partial class AddProcessingTicket
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UtrkePasa.Domain.Entities.Dog", b =>
                {
                    b.Property<int>("DogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("dog_Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DogId"));

                    b.Property<string>("dog_Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("dog_Name");

                    b.Property<int>("race_Odds_Id")
                        .HasColumnType("integer");

                    b.HasKey("DogId");

                    b.HasIndex("race_Odds_Id");

                    b.ToTable("Dog");
                });

            modelBuilder.Entity("UtrkePasa.Domain.Entities.ProcessingTicket", b =>
                {
                    b.Property<int>("ProcessingTicketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("processing_Ticket_Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProcessingTicketId"));

                    b.Property<string>("ProcessingTicketStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("processing_Ticket_Status");

                    b.Property<int>("RaceHistoryId")
                        .HasColumnType("integer")
                        .HasColumnName("race_History_Id");

                    b.Property<int>("RaceId")
                        .HasColumnType("integer")
                        .HasColumnName("race_Id");

                    b.HasKey("ProcessingTicketId");

                    b.HasIndex("RaceHistoryId");

                    b.HasIndex("RaceId");

                    b.ToTable("ProcessingTicket");
                });

            modelBuilder.Entity("UtrkePasa.Domain.Entities.Race", b =>
                {
                    b.Property<int>("RaceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("race_Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RaceId"));

                    b.PrimitiveCollection<List<string>>("DogStartingPosition")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("dog_Starting_Position");

                    b.Property<DateTimeOffset>("EndOfTheRace")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_Of_The_Race");

                    b.Property<string>("RaceName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("race_Name");

                    b.Property<string>("RaceStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("race_Status");

                    b.Property<string>("ResultOfRace")
                        .HasColumnType("text")
                        .HasColumnName("result_Of_Race");

                    b.Property<DateTimeOffset>("StartOfBetting")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_Of_Betting");

                    b.Property<DateTimeOffset>("StartOfTheRace")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_Of_The_Race");

                    b.HasKey("RaceId");

                    b.ToTable("Race");
                });

            modelBuilder.Entity("UtrkePasa.Domain.Entities.RaceHistory", b =>
                {
                    b.Property<int>("HistoryRaceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("history_Race_Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("HistoryRaceId"));

                    b.Property<int>("dog_Id")
                        .HasColumnType("integer");

                    b.Property<int>("finale_Position")
                        .HasColumnType("integer");

                    b.Property<bool>("is_Winner")
                        .HasColumnType("boolean");

                    b.Property<int>("race_Id")
                        .HasColumnType("integer");

                    b.HasKey("HistoryRaceId");

                    b.HasIndex("dog_Id");

                    b.HasIndex("race_Id");

                    b.ToTable("RaceHistory");
                });

            modelBuilder.Entity("UtrkePasa.Domain.Entities.RaceOdds", b =>
                {
                    b.Property<int>("race_Odds_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("race_Odds_Id"));

                    b.Property<int?>("RaceId")
                        .HasColumnType("integer");

                    b.Property<string>("expected_Result")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("odds")
                        .HasColumnType("real");

                    b.Property<int>("race_Id")
                        .HasColumnType("integer");

                    b.HasKey("race_Odds_Id");

                    b.HasIndex("RaceId");

                    b.ToTable("RaceOdds");
                });

            modelBuilder.Entity("UtrkePasa.Domain.Entities.Ticket", b =>
                {
                    b.Property<int>("ticket_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ticket_Id"));

                    b.Property<decimal>("paid_For_Ticket")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("placed_At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("race_Id")
                        .HasColumnType("integer");

                    b.Property<int>("race_Odds_Id")
                        .HasColumnType("integer");

                    b.Property<int>("user_Id")
                        .HasColumnType("integer");

                    b.HasKey("ticket_Id");

                    b.HasIndex("race_Id");

                    b.HasIndex("race_Odds_Id");

                    b.HasIndex("user_Id");

                    b.ToTable("Ticket");
                });

            modelBuilder.Entity("UtrkePasa.Domain.Entities.User", b =>
                {
                    b.Property<int>("user_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("user_Id"));

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("surname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("wallet_State")
                        .HasColumnType("real");

                    b.HasKey("user_Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("UtrkePasa.Domain.Entities.Dog", b =>
                {
                    b.HasOne("UtrkePasa.Domain.Entities.RaceOdds", "race_Odds")
                        .WithMany()
                        .HasForeignKey("race_Odds_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("race_Odds");
                });

            modelBuilder.Entity("UtrkePasa.Domain.Entities.ProcessingTicket", b =>
                {
                    b.HasOne("UtrkePasa.Domain.Entities.RaceHistory", "raceHistory")
                        .WithMany()
                        .HasForeignKey("RaceHistoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UtrkePasa.Domain.Entities.Race", "Race")
                        .WithMany()
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Race");

                    b.Navigation("raceHistory");
                });

            modelBuilder.Entity("UtrkePasa.Domain.Entities.RaceHistory", b =>
                {
                    b.HasOne("UtrkePasa.Domain.Entities.Dog", "Dog")
                        .WithMany("raceHistory")
                        .HasForeignKey("dog_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UtrkePasa.Domain.Entities.Race", "Race")
                        .WithMany("raceHistory")
                        .HasForeignKey("race_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dog");

                    b.Navigation("Race");
                });

            modelBuilder.Entity("UtrkePasa.Domain.Entities.RaceOdds", b =>
                {
                    b.HasOne("UtrkePasa.Domain.Entities.Race", "race")
                        .WithMany("odds")
                        .HasForeignKey("RaceId");

                    b.Navigation("race");
                });

            modelBuilder.Entity("UtrkePasa.Domain.Entities.Ticket", b =>
                {
                    b.HasOne("UtrkePasa.Domain.Entities.Race", "race")
                        .WithMany("tickets")
                        .HasForeignKey("race_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UtrkePasa.Domain.Entities.RaceOdds", "race_Odds")
                        .WithMany()
                        .HasForeignKey("race_Odds_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UtrkePasa.Domain.Entities.User", "user")
                        .WithMany("tickets")
                        .HasForeignKey("user_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("race");

                    b.Navigation("race_Odds");

                    b.Navigation("user");
                });

            modelBuilder.Entity("UtrkePasa.Domain.Entities.Dog", b =>
                {
                    b.Navigation("raceHistory");
                });

            modelBuilder.Entity("UtrkePasa.Domain.Entities.Race", b =>
                {
                    b.Navigation("odds");

                    b.Navigation("raceHistory");

                    b.Navigation("tickets");
                });

            modelBuilder.Entity("UtrkePasa.Domain.Entities.User", b =>
                {
                    b.Navigation("tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
