using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace UtrkePasa.Domain.Migrations
{
    /// <inheritdoc />
    public partial class AddRegister : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {

            migrationBuilder.Sql(@"

                ALTER TABLE ""Ticket""
                ALTER COLUMN ""is_Winning_Ticket"" DROP NOT NULL;

                CREATE TABLE ""Register""(
                    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    app_name text NOT NULL,
                    app_guid uuid NOT NULL,
                    timestamp timestamp with time zone NOT NULL
                );
                
            
            
            ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {

            migrationBuilder.Sql(@"

                ALTER TABLE ""Ticket""
                ALTER COLUMN ""is_Winning_Ticket"" SET NOT NULL;

                DROP TABLE ""Register"";
            ");

        }
    }
}
